const traductionOfAboutMe = {
    title:{
        ES:"SOBRE MI",
        EN:"ABOUT ME"
    },
    firstParagraph:{
        ES: "Hola! Mi nombre es Santino, soy un apasionado a la programacion por lo grandes retos que debo afrontar dia. Me encanta ponerme a prueba todos los dias con challenges que me voy encontrando. Me gusta leer muchos libros de superacion personal y grupal o entrenar en mis tiempos libres, me ayuda a desconectarme y poder cargar pilas. Suelo destacarme un mi organizacion y la discplina que logre inculcar en mis años como deportista de alto rendimiento. Me considero un programador full-stack, no solo por mis conocimientos en ambos campos, sino tambien por mi capacidad de poder desempeñarme en los dos sectores con fluidez. En todos los proyectos donde tuve la oportunidad de estar presente, participe tanto en el back como en el front.",
        EN: "Hello! My name is Santino, I am passionate about programming because of the great challenges I have to face every day. I love putting myself to the test every day with challenges that I find. I like to read many books on personal and group improvement or training in my free time, it helps me disconnect and be able to recharge my batteries. I usually stand out for my organization and the discipline that I managed to instill in my years as a high-performance athlete. I consider myself a full-stack programmer, not only because of my knowledge in both fields, but also because of my ability to perform fluently in both sectors. In all the projects where I had the opportunity to be present, I participated both in the back and in the front."
    },
    secondParagraph:{
        ES:"Me gusta mucho practicar deportes, no importa cual sea, siempre trato de hacer deporte para despejar mi cabeza y refrescar ideas nuevas. En mis dias como estudiante de Henry Bootcamp, fui Teaching Assistant, donde junto con un compañero, lidere un grupo de estudiantes para que puedan llegar a un mismo objetvo en comun y culminar de la mejor manera el Bootcamp. En esta instancia me aporto muchas cosas, pero sobre todo aprendi la importancia de las habilidades blandas o soft skills. Recibi capacitaciones sobre manejo de emociones propias y ajenas, manejo de conversaciones, entre muchisimas cosas que me ayudan a poder desempeñarme en mis trabajos, en poder alcanzar el 200% de mi potencial y tambien el de la gente que me rodea. Me gusta priorizar la perseverancia por sobre la perfeccion, pero siempre busco la perfeccion en todos mis proyectos y trabajos, al fin y al cabo las empresas y personas buscan los mejores resultados.... ",
        EN:"I really like playing sports, no matter what it is, I always try to play sports to clear my head and refresh new ideas. In my days as a Henry Bootcamp student, I was a Teaching Assistant, where together with a colleague, I led a group of students so that they can reach the same common goal and complete the Bootcamp in the best way. In this instance I contribute many things, but above all I learned the importance of soft skills. I received training on managing my own and others' emotions, managing conversations, among many things that help me to be able to perform in my jobs, to be able to reach 200% of my potential and also that of the people around me. I like to prioritize perseverance over perfection, but I always look for perfection in all my projects and jobs, after all, companies and people look for the best results...."
    }
}

export default traductionOfAboutMe